config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("users/", include("schablone.users.urls", namespace="users")),
    path("checkout/", include("schablone.checkout.urls", namespace="checkout")),
    path("ht/", include("health_check.urls")),
    path("hijack/", include("hijack.urls")),
    path("clearcache/", include("clearcache.urls")),
    path("stripe/", include("djstripe.urls", namespace="djstripe")),
    path("", include("project.app.urls", namespace="app")),
]

if settings.DEBUG:
    import debug_toolbar
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]
    urlpatterns += [path("herald/", include("herald.urls"))]

project_name/app/urls.py
from django.urls import path

from {{project_name}}.app.views import DashboardView

app_name = "app"

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
]

project_name/users/urls.py
from django.urls import path
from sesame.views import LoginView

from {{project_name}}.users.views import EmailLoginView

app_name = "users"
urlpatterns = [
    path("login/", EmailLoginView.as_view(), name="email_login"),
    path("login/auth/", LoginView.as_view(), name="login"),
]

project_name/app/models.py
# from django.db import models

# Create your models here.

project_name/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for {{project_name}}.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

project_name/users/forms.py
from django import forms
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class EmailLoginForm(forms.Form):
    email = forms.EmailField()

project_name/app/views.py
from django.views.generic import TemplateView


class DashboardView(TemplateView):
    template_name = "app/dashboard.html"

project_name/users/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import FormView
from sesame.utils import get_query_string

from {{project_name}}.users.forms import EmailLoginForm

User = get_user_model()


class EmailLoginView(FormView):
    template_name = "users/email_login.html"
    form_class = EmailLoginForm

    def get_or_create_user(self, email: str) -> "User":
        """Find or create a user with this email address."""
        User = get_user_model()
        user = User.objects.filter(email=email).first()
        if user is None:
            user = User.objects.create(email=email, username=email)
            # user.set_unusable_password()  # type: ignore
        return user

    def create_link(self, user: "User") -> str:
        """Create a login link for this user."""
        link = reverse("users:login")
        link = self.request.build_absolute_uri(link)
        link += get_query_string(user)
        return link

    def send_email(self, user, link):
        """Send an email with this login link to this user."""
        user.email_user(
            subject="[django-sesame] Log in to our app",
            message=f"""\
Hello,

You requested that we send you a link to log in to our app:

    {link}

Thank you for using django-sesame!
""",
        )

    def email_submitted(self, email):
        user = self.get_or_create_user(email)
        link = self.create_link(user)
        self.send_email(user, link)

    def form_valid(self, form):
        self.email_submitted(form.cleaned_data["email"])
        return render(self.request, "users/email_login_success.html")

project_name/templates/base.html
{% load static i18n compress tailwind_cli%}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}" class="h-full bg-gray-50">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}{% endraw %}{{project_name}}{% raw %}{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{{project_name}}">
    <meta name="author" content="Josef Erben">

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
      <!-- Your stuff: Third-party CSS libraries go here -->

      <!-- This file stores project-specific CSS -->
      {% compress css %}
        {% tailwind_css %}
      {% endcompress %}
    {% endblock %}
    <!-- Le javascript
    ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block javascript %}
      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->
      {% compress js %}
        <script defer src="{% static 'js/project.js' %}"></script>
      {% endcompress %}

    {% endblock javascript %}
  </head>

  <body class="h-full">
    {% block content %}
    {% endblock content %}
  </body>
</html>

project_name/templates/form_snippet.html
{% raw %}{% load widget_tweaks %}

<div class="grid grid-cols-1 gap-6">
  {% if form.non_field_errors %}
    <span class="text-sm text-center text-red-500">{{ form.non_field_errors }}</span>
  {% endif %}
  {% for field in form %}
    <label class="block">
      <span class="text-gray-700">{{ field.label }}</span>
      <!-- Checkbox -->
      {% if field|field_type == 'booleanfield' %}
        {{ field|add_class:"rounded border-gray-300 text-indigo-600 shadow-sm focus:border-indigo-300 focus:ring focus:ring-offset-0 focus:ring-indigo-200 focus:ring-opacity-50" }}
        <span class="text-sm text-red-500">{{ field.errors }}</span>
        <!-- Date -->
      {% elif field|field_type == 'datefield' %}
        {{ field|add_class:"mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" }}
        <span class="text-sm text-red-500">{{ field.errors }}</span>
        <!-- Email -->
      {% elif field|field_type == 'emailfield' %}
        {{ field|add_class:"mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"|attr:"placeholder:" }}
        <span class="text-sm text-red-500">{{ field.errors }}</span>
        <!-- Password -->
      {% elif field|field_type == 'passwordfield' %}
        {{ field|add_class:"mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"|attr:"placeholder:" }}
        <span class="text-sm text-red-500">{{ field.errors }}</span>
      {% else %}
        <!-- Fallback -->
        {{ field }}
      {% endif %}
    </label>
  {% endfor %}
</div>
{%- endraw %}

project_name/templates/landing.html
{% raw %}{% extends 'base.html' %}

{% block content %}
  <div class="overflow-hidden relative bg-white">
    <div class="mx-auto max-w-7xl">
      <div class="relative z-10 pb-8 bg-white sm:pb-16 md:pb-20 lg:pb-28 lg:w-full lg:max-w-2xl xl:pb-32">
        <svg class="hidden absolute inset-y-0 right-0 w-48 h-full text-white transform translate-x-1/2 lg:block" fill="currentColor" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">
          <polygon points="50,0 100,0 50,100 0,100" />
        </svg>

        <div>
          <div class="relative px-4 pt-6 sm:px-6 lg:px-8">
            <nav class="flex relative justify-between items-center sm:h-10 lg:justify-start" aria-label="Global">
              <div class="flex flex-grow flex-shrink-0 items-center lg:flex-grow-0">
                <div class="flex justify-between items-center w-full md:w-auto">
                  <a href="{% url 'app:dashboard' %}">
                    <span class="sr-only">Your Company</span>
                    <img alt="Your Company" class="w-auto h-8 sm:h-10" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600">
                  </a>
                  <div class="flex items-center -mr-2 md:hidden">
                    <button type="button" class="inline-flex justify-center items-center p-2 text-gray-400 bg-white rounded-md hover:text-gray-500 hover:bg-gray-100 focus:ring-2 focus:ring-inset focus:ring-indigo-500 focus:outline-none" aria-expanded="false">
                      <span class="sr-only">Open main menu</span>
                      <!-- Heroicon name: outline/bars-3 -->
                      <svg class="w-6 h-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
                      </svg>
                    </button>
                  </div>
                </div>
              </div>
              <div class="hidden md:block md:pr-4 md:ml-10 md:space-x-8">
                <a href="#" class="font-medium text-gray-500 hover:text-gray-900">Product</a>

                <a href="#" class="font-medium text-gray-500 hover:text-gray-900">Features</a>

                <a href="#" class="font-medium text-gray-500 hover:text-gray-900">Marketplace</a>

                <a href="#" class="font-medium text-gray-500 hover:text-gray-900">Company</a>

                <a href="{% url 'users:email_login' %}" class="font-medium text-indigo-600 hover:text-indigo-500">Log in</a>
              </div>
            </nav>
          </div>

          <!--
          Mobile menu, show/hide based on menu open state.

          Entering: "duration-150 ease-out"
            From: "opacity-0 scale-95"
            To: "opacity-100 scale-100"
          Leaving: "duration-100 ease-in"
            From: "opacity-100 scale-100"
            To: "opacity-0 scale-95"
        -->
          <div id="mobileNav" data-state="closed" class="absolute inset-x-0 top-0 z-10 p-2 opacity-0 transition transform origin-top-right scale-95 md:hidden">
            <div class="overflow-hidden bg-white rounded-lg ring-1 ring-black ring-opacity-5 shadow-md">
              <div class="flex justify-between items-center px-5 pt-4">
                <div>
                  <img class="w-auto h-8" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600" alt="">
                </div>
                <div class="-mr-2">
                  <button onclick="toggleMobileNav()" type="button" class="inline-flex justify-center items-center p-2 text-gray-400 bg-white rounded-md hover:text-gray-500 hover:bg-gray-100 focus:ring-2 focus:ring-inset focus:ring-indigo-500 focus:outline-none">
                    <span class="sr-only">Close main menu</span>
                    <!-- Heroicon name: outline/x-mark -->
                    <svg class="w-6 h-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                  </button>
                </div>
              </div>
              <div class="px-2 pt-2 pb-3 space-y-1">
                <a href="#" class="block py-2 px-3 text-base font-medium text-gray-700 rounded-md hover:text-gray-900 hover:bg-gray-50">Product</a>

                <a href="#" class="block py-2 px-3 text-base font-medium text-gray-700 rounded-md hover:text-gray-900 hover:bg-gray-50">Features</a>

                <a href="#" class="block py-2 px-3 text-base font-medium text-gray-700 rounded-md hover:text-gray-900 hover:bg-gray-50">Marketplace</a>

                <a href="#" class="block py-2 px-3 text-base font-medium text-gray-700 rounded-md hover:text-gray-900 hover:bg-gray-50">Company</a>
              </div>
              <a href="#" class="block py-3 px-5 w-full font-medium text-center text-indigo-600 bg-gray-50 hover:bg-gray-100">Log in</a>
            </div>
          </div>
        </div>

        <main class="px-4 mx-auto mt-10 max-w-7xl sm:px-6 sm:mt-12 md:mt-16 lg:px-8 lg:mt-20 xl:mt-28">
          <div class="sm:text-center lg:text-left">
            <h1 class="text-4xl font-bold tracking-tight text-gray-900 sm:text-5xl md:text-6xl">
              <span class="block xl:inline">Data to enrich your</span>
              <span class="block text-indigo-600 xl:inline">online business</span>
            </h1>
            <p class="mt-3 text-base text-gray-500 sm:mx-auto sm:mt-5 sm:max-w-xl sm:text-lg md:mt-5 md:text-xl lg:mx-0">Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui lorem cupidatat commodo. Elit sunt amet fugiat veniam occaecat fugiat aliqua.</p>
            <div class="mt-5 sm:flex sm:justify-center sm:mt-8 lg:justify-start">
              <div class="rounded-md shadow">
                <a href="#" class="flex justify-center items-center py-3 px-8 w-full text-base font-medium text-white bg-indigo-600 rounded-md border border-transparent md:py-4 md:px-10 md:text-lg hover:bg-indigo-700">Get started</a>
              </div>
              <div class="mt-3 sm:mt-0 sm:ml-3">
                <a href="#" class="flex justify-center items-center py-3 px-8 w-full text-base font-medium text-indigo-700 bg-indigo-100 rounded-md border border-transparent md:py-4 md:px-10 md:text-lg hover:bg-indigo-200">Live demo</a>
              </div>
            </div>
          </div>
        </main>
      </div>
    </div>
    <div class="lg:absolute lg:inset-y-0 lg:right-0 lg:w-1/2">
      <img class="object-cover w-full h-56 sm:h-72 md:h-96 lg:w-full lg:h-full" src="https://images.unsplash.com/photo-1551434678-e076c223a692?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2850&q=80" alt="">
    </div>
  </div>
{% endblock content %}
{%- endraw %}