config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("users/", include("schablone.users.urls", namespace="users")),
    path("checkout/", include("schablone.checkout.urls", namespace="checkout")),
    path("ht/", include("health_check.urls")),
    path("hijack/", include("hijack.urls")),
    path("clearcache/", include("clearcache.urls")),
    path("stripe/", include("djstripe.urls", namespace="djstripe")),
    path("", include("project.app.urls", namespace="app")),
]

if settings.DEBUG:
    import debug_toolbar
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]
    urlpatterns += [path("herald/", include("herald.urls"))]

project/app/urls.py
from django.urls import path

from .views import DashboardView, SettingsView

app_name = "app"

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("settings/", SettingsView.as_view(), name="settings"),
]

project/app/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django_extensions.db.models import TimeStampedModel

User = get_user_model()


class Customer(TimeStampedModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="customer")
    # put your fields here

project/app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = "app/dashboard.html"


class SettingsView(LoginRequiredMixin, TemplateView):
    template_name = "app/settings.html"

project/templates/app/base.html
{% extends "base.html" %}
{% block content %}
  <header class="flex justify-between px-4 sm:px-6 lg:px-8 max-w-7xl mt-4 items-center">
    <a href="{% url 'app:dashboard' %}"
       class="text-indigo-600 font-semibold text-xl hover:cursor-pointer">Project</a>
    <nav class="flex gap-x-5 md:gap-x-11 text-sm font-semibold leading-6 text-gray-700">
      <a href="{% url 'app:dashboard' %}">Dashboard</a>
      <a href="#">FAQs</a>
    </nav>
    <a href="{% url 'app:settings' %}" class="-m-1.5 p-1.5 text-gray-600">
      <span class="sr-only">Your profile</span>
      <svg xmlns="http://www.w3.org/2000/svg"
           fill="none"
           viewBox="0 0 24 24"
           stroke-width="1.5"
           stroke="currentColor"
           class="w-8 h-8">
        <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0012 15.75a7.488 7.488 0 00-5.982 2.975m11.963 0a9 9 0 10-11.963 0m11.963 0A8.966 8.966 0 0112 21a8.966 8.966 0 01-5.982-2.275M15 9.75a3 3 0 11-6 0 3 3 0 016 0z" />
      </svg>
    </a>
  </header>
  <main>
    <div class="relative isolate overflow-hidden pt-16">
      {% block content_app %}
      {% endblock content_app %}
    </div>
  </main>
{% endblock content %}

project/templates/app/dashboard.html
{% extends "app/base.html" %}
{% load widget_tweaks %}
{% block content_app %}
  <main class="px-4 sm:px-20 md:px-32 sm:mt-12 max-w-7xl">
    <div class="flex justify-between">
      <h1 class="mt-1 text-2xl md:text-3xl leading-relaxed font-semibold text-gray-800">My things</h1>
      <button type="button"
              class="inline-flex items-center gap-x-2 rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
        <svg xmlns="http://www.w3.org/2000/svg"
             fill="none"
             viewBox="0 0 24 24"
             strokeWidth="1.5"
             stroke="currentColor"
             class="-ml-0.5 h-5 w-5">
          <path strokeLinecap="round" strokeLinejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
        </svg>
        Add a thing
      </button>
    </div>
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 mt-6">
      <article class="bg-white rounded shadow-lg px-4 py-3">
        <h2 class="text-lg font-semibold text-gray-600 mb-4">Thing 1</h2>
        <p>This is just the first thing among many other things.</p>
      </article>
    </div>
  </main>
{% endblock content_app %}

project/templates/app/settings.html
{% extends "app/base.html" %}
{% load widget_tweaks %}
{% block content_app %}
  <main class="px-4 sm:px-20 md:px-32 sm:mt-12 max-w-7xl">
    <div class="flex justify-between">
      <h1 class="mt-1 text-2xl md:text-3xl leading-relaxed font-semibold text-gray-800">Settings</h1>
      <button type="button"
              class="rounded-md bg-red-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
        Logout
      </button>
    </div>
    <article class="bg-white rounded-lg shadow-lg px-4 py-3 w-full mt-6">Some user settings</article>
  </main>
{% endblock content_app %}